
spring:
  profiles:
    active: development
  jpa:
    hibernate:
      ddl-auto: validate



    
  h2:
    console:
      enabled: true
 
security:
  basic:
    enabled: false
    
management:
  security:
    enabled: true
    
server:
  port: 8762    

turbine:  
  appConfig: customerservice1

  
    

     

---
spring:
  profiles: development
  
flyway:
  enabled: false
  baseline-on-migrate: false 
  

 
samplecustomer.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:~/test
  username: sa
  password: sa
  accessToUnderlyingConnectionAllowed: true

--- 
 spring: 
  profiles: cloud
  
 


 flyway:  
  enabled: false
  init-on-migrate: false
 
 samplecustomer.datasource:
    driverClassName: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:test;
    username: sa
    password: sa
    accessToUnderlyingConnectionAllowed: true

