

CREATE TABLE IF NOT EXISTS CUSTOMER (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) not null,
	address varchar(255) not null,
	username varchar(255) not null,
	password varchar(255) not null,
	 PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS UserDetail (
	userId BIGINT GENERATED BY DEFAULT AS IDENTITY,	
	username varchar(255) not null,
	password varchar(255) not null,
	roles varchar(255) not null,
	 PRIMARY KEY (userId)
);
