FROM java:8

ENV JAR SampleProducts-0.0.1-SNAPSHOT.jar
ENV MAIN_CLASS com.newt.SampleProductsApplication

ADD "SampleCustomers-1.0.0-SNAPSHOT.war" "SampleCustomers-1.0.0-SNAPSHOT.war"

CMD java  -jar SampleProducts-0.0.1-SNAPSHOT.war


